name: doctor_fy
description: New doctor fy app 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_ui: ^1.6.8
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^14.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  geolocator: ^9.0.2
  get_it: ^7.6.0
  go_router: ^9.0.0
  image_picker: ^1.0.0
  intl: ^0.18.0
  loader_overlay: ^2.2.0
  permission_handler: ^10.3.0
  share_plus: ^7.0.2
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  supabase_flutter: ^1.10.4

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - .env

