name: doctor_fy
description: New doctor fy app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.9.0-0
  audioplayers: ^4.1.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  chat_bubbles:
    path: ./packages/chat_bubbles
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.2.1+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^14.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_onboarding_slider: ^1.0.9
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  go_router: ^9.0.0
  image_picker: ^1.0.0
  intl: ^0.18.0
  intl_phone_field: ^3.2.0
  loader_overlay: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^10.3.0
  settings_ui: ^2.0.2
  share_plus: ^7.0.2
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  supabase_flutter: ^1.10.4
  swipe_to: ^1.0.2
  timeago: ^3.4.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter_native_splash:
  color: "#000000"
  image: true
  color_dark: "#000000"
  android_12:
    image: assets/images/doctorfy_logo.png
    icon_background_color: "#000000"
    image_dark: assets/images/doctorfy_logo.png
    icon_background_color_dark: "#000000"
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "assets/images/doctorfy_logo_negro.png"
  image_path: "assets/images/doctorfy_logo_negro.png"
  image_path_ios: "assets/images/doctorfy_logo_negro.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/svgs/
